#!/usr/bin/env bash

function add_tag() {
  docker tag $IMAGE_NAME $DOCKER_REPO:$1
  docker push $DOCKER_REPO:$1
}

CID=$(docker run -d $IMAGE_NAME)
sleep 10s
BUILD=$(docker exec $CID tvheadend -v | awk -F'[_ ]' '{print $NF}' | awk -F'[_~]' '{print $1}')
docker rm -f $CID

add_tag $DOCKER_TAG
add_tag $DOCKER_TAG-$BUILD

if [ "${DOCKER_TAG}" == "amd64-latest" ]; then
	add_tag "latest"
elif [ "${DOCKER_TAG}" == "amd64-stable" ]; then
	add_tag "stable"
fi

exit $?
