name: docker-buildx

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 21 * * 5"

env:
  DOCKERHUB_USER: wiserain
  DOCKERHUB_REPO: tvheadend

jobs:
  build-tvhbase-latest:
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvhbase
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'latest'
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: latest
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: latest

  build-tvhbase-stable:
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvhbase
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'stable'
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: stable
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: stable

  build-tvhbase-ubuntu:
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvhbase
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'latest'
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: ubuntu
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile.ubuntu
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: ubuntu

  build-tvheadend-latest:
    needs: build-tvhbase-latest
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        env:
          IMAGE_FROM: wiserain/tvhbase:latest
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvheadend
          echo ::set-output name=image_tag::latest
          echo ::set-output name=image_from::${IMAGE_FROM}
          CID=$(docker run -d $IMAGE_FROM)
          BUILD=$(docker exec $CID tvheadend -v | awk -F'[_ ]' '{print $NF}' | awk -F'[_~]' '{print $1}')
          docker rm -f $CID
          echo ::set-output name=tvh_build::${BUILD}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: ${{ steps.vars.outputs.image_tag }},${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile
          buildArg: BASE_IMAGE=${{ steps.vars.outputs.image_from }}
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: ${{ steps.vars.outputs.image_tag }}, ${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}

  build-tvheadend-stable:
    needs: build-tvhbase-stable
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        env:
          IMAGE_FROM: wiserain/tvhbase:stable
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvheadend
          echo ::set-output name=image_tag::stable
          echo ::set-output name=image_from::${IMAGE_FROM}
          CID=$(docker run -d $IMAGE_FROM)
          BUILD=$(docker exec $CID tvheadend -v | awk -F'[_ ]' '{print $NF}' | awk -F'[_~]' '{print $1}')
          docker rm -f $CID
          echo ::set-output name=tvh_build::${BUILD}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: ${{ steps.vars.outputs.image_tag }},${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile
          buildArg: BASE_IMAGE=${{ steps.vars.outputs.image_from }}
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: ${{ steps.vars.outputs.image_tag }}, ${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}

  build-tvheadend-ubuntu:
    needs: build-tvhbase-ubuntu
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        env:
          IMAGE_FROM: wiserain/tvhbase:ubuntu
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvheadend
          echo ::set-output name=image_tag::ubuntu
          echo ::set-output name=image_from::${IMAGE_FROM}
          CID=$(docker run -d $IMAGE_FROM)
          BUILD=$(docker exec $CID tvheadend -v | awk -F'[_ ]' '{print $NF}' | awk -F'[_~]' '{print $1}')
          docker rm -f $CID
          echo ::set-output name=tvh_build::${BUILD}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: ${{ steps.vars.outputs.image_tag }},${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile.ubuntu
          buildArg: BASE_IMAGE=${{ steps.vars.outputs.image_from }}
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: ${{ steps.vars.outputs.image_tag }}, ${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}

  build-tvheadend-latest-ns:
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        env:
          IMAGE_FROM: linuxserver/tvheadend:latest
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvheadend
          echo ::set-output name=image_tag::latest-ns
          echo ::set-output name=image_from::${IMAGE_FROM}
          CID=$(docker run -d $IMAGE_FROM)
          BUILD=$(docker exec $CID tvheadend -v | awk -F'[_ ]' '{print $NF}' | awk -F'[_~]' '{print $1}')
          docker rm -f $CID
          echo ::set-output name=tvh_build::${BUILD}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: ${{ steps.vars.outputs.image_tag }},${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile
          buildArg: BASE_IMAGE=${{ steps.vars.outputs.image_from }}
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: ${{ steps.vars.outputs.image_tag }}, ${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}

  build-tvheadend-stable-ns:
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        env:
          IMAGE_FROM: linuxserver/tvheadend:release-4.2
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::tvheadend
          echo ::set-output name=image_tag::stable-ns
          echo ::set-output name=image_from::${IMAGE_FROM}
          CID=$(docker run -d $IMAGE_FROM)
          BUILD=$(docker exec $CID tvheadend -v | awk -F'[_ ]' '{print $NF}' | awk -F'[_~]' '{print $1}')
          docker rm -f $CID
          echo ::set-output name=tvh_build::${BUILD}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          tag: ${{ steps.vars.outputs.image_tag }},${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}
          imageName: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
          dockerFile: Dockerfile
          buildArg: BASE_IMAGE=${{ steps.vars.outputs.image_from }}
          publish: true
          platform: ${{ steps.vars.outputs.buildx_platforms }}
          dockerHubUser: ${{ steps.vars.outputs.dockerhub_user }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: ${{ steps.vars.outputs.image_tag }}, ${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.tvh_build }}

  pushrm:
    needs:
      - build-tvheadend-latest
      - build-tvheadend-stable
      - build-tvheadend-ubuntu
      - build-tvheadend-latest-ns
      - build-tvheadend-stable-ns
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=github_desc::$(curl -sX GET https://api.github.com/repos/wiserain/docker-tvheadend | jq -r .description)
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ env.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        with:
          destination_container_repo: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          provider: dockerhub
          short_description: ${{ steps.vars.outputs.github_desc }}
          readme_file: 'README.md'
