#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/comskip

# copy config
[[ ! -e /config/dvr/config ]] && \
    mkdir -p /config/dvr/config && \
    cp /defaults/7a5edfbe189851e5b1d1df19c93962f0 /config/dvr/config/7a5edfbe189851e5b1d1df19c93962f0
[[ ! -e /config/comskip/comskip.ini ]] && \
    cp /defaults/comskip.ini.org /config/comskip/comskip.ini
[[ ! -e /config/config ]] && \
    cp /defaults/config /config/config

# permissions
echo "Setting permissions"
abc_dirs=( \
    /config \
    /picons \
)
for i in "${abc_dirs[@]}"; do
    find ${i} \! \( -uid $(id -u abc) -gid $(id -g abc) \) -print0 | \
        xargs -0 --no-run-if-empty chown -h abc:abc
done
