#!/usr/bin/with-contenv bash

tmpdir=$(mktemp -d)

# prepare epg2xml
EPG2XML_GIT="https://github.com/${EPG2XML_FROM:-wiserain}/epg2xml.git"
if ! (git clone --quiet "${EPG2XML_GIT}" > /dev/null ${tmpdir}); then
	echo "ERROR: Invalid repository url for epg2xml"
	echo "ERROR: ${EPG2XML_GIT}"
	exit 1
fi

if [[ ! -z "${EPG2XML_VER}" ]] && [[ -d "${tmpdir}/.git" ]]; then
	echo " INFO: Checking out to \"${EPG2XML_VER}\""
	cd ${tmpdir} && git checkout "${EPG2XML_VER}"
fi

# make folder
[[ ! -d "/epg2xml/xml" ]] && mkdir /epg2xml/xml

# install epg2xml.py
if [[ "${UPDATE_EPG2XML}" == "1" ]] || [[ ! -f "/epg2xml/epg2xml.py" ]]; then
	echo "Installing epg2xml.py ..."
	mv ${tmpdir}/epg2xml.py /epg2xml/ 2>/dev/null
else
	echo "Using existing epg2xml.py. Skipping installation ..."
fi

# install epg2xml.json as well if not exist
if [[ ! -f /epg2xml/epg2xml.json ]]; then
	echo "Installing epg2xml.json ..."
	mv ${tmpdir}/epg2xml.json /epg2xml/ 2>/dev/null
else
	echo "Using existing epg2xml.json. Skipping installation ..."
fi

# update Channel.json
if [[ ! -f /epg2xml/Channel.json ]] || [[ "${UPDATE_CHANNEL}" == "1" ]]; then
	echo "Installing Channel.json ..."
	mv ${tmpdir}/Channel.json /epg2xml/ 2>/dev/null
else
	echo "Using existing Channel.json. Skipping installation ..."
fi

# permissions
chown -R abc:abc \
	/epg2xml

# cleanup
rm -rf /tmp/*
